chore: allow renovate @types/node update
neostandard/neostandard pull request #97
Opened 2024-07-02 21:23 UTC by jerome-benoit

It's a dev dep.

* Add rule for grouping major dev deps
* Dedupe package-lock.json: renovate lock file maintenance PR merge has
  introduced typescript-eslint related deps duplicates

2024-07-03 06:40 UTC, mcollina approved these changes
lgtm

2024-07-04 08:54 UTC, voxpelli requested changes
> Dedupe package-lock.json: renovate lock file maintenance PR merge has
introduced typescript-eslint related deps duplicates

This is odd, as Renovate [lock file maintenance](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance) is described as doing:

> When Renovate performs lockFileMaintenance it deletes the lock file and runs the relevant package manager. That package manager creates a new lock file, where all dependency versions are updated to the latest version. Renovate then commits that lock file to the update branch and creates the lock file update PR.

I wonder what makes it do this 🤔

2024-07-04 08:54 UTC, voxpelli commented on renovate.json
> +    },
I prefer to not group major dev dependencies as the major bump indicate that they are breaking in some way and bundling many such together can make it harder to merge as a blocking breaking change from any one dependency will block the merging of them all

2024-07-04 08:54 UTC, voxpelli commented on renovate.json
> -  "ignoreDeps": ["@types/node"],
Good call 👍 Its covered by `helpers:disableTypesNodeMajor` anyway :)

2024-07-04 09:22 UTC, jerome-benoit commented
> I wonder what makes it do this 🤔

Renovate does not run `npm dedupe` on PR maintenance.

2024-07-04 09:58 UTC, voxpelli commented
> > I wonder what makes it do this 🤔
> 
> Renovate does not run `npm dedupe` on PR maintenance.

One can make it do so: https://docs.renovatebot.com/configuration-options/#postupdateoptions

But in this case the normal hoisting should be enough, the `npm dedupe` only differs by preferring sharing dependencies rather than newest dependencies, not sure why it caused duplication in this case

2024-07-04 10:02 UTC, jerome-benoit commented
> > Renovate does not run `npm dedupe` on PR maintenance.
> 
> One can make it do so: https://docs.renovatebot.com/configuration-options/#postupdateoptions
> 

In that PR? 

> But in this case the normal hoisting should be enough, the `npm dedupe` only differs by preferring sharing dependencies rather than newest dependencies, not sure why it caused duplication in this case

Deduping algo is not triggered by default at install/update in npm/pnpm, probably for performance reason.

2024-07-04 10:17 UTC, voxpelli commented
> Deduping algo is not triggered by default at install/update in npm/pnpm, probably for performance reason.

They themselves [note](https://docs.npmjs.com/cli/v10/commands/npm-dedupe):

> because npm favors updates by default, even when doing so causes duplication

I dug into why this duplication happens:

It's because [@typescript-eslint/utils](https://www.npmjs.com/package/@typescript-eslint/utils) has a `alpha40` release but [typescript-eslint](https://www.npmjs.com/package/typescript-eslint) is still at `alpha39` and `@stylistic/eslint-plugin-ts@2.6.0-beta.0` and `@stylistic/eslint-plugin-plus@2.6.0-beta.0` do like us and and pull in the very latest alpha release of `@typescript-eslint/utils` and but `typescript-eslint@alpha39`  specifically requests `@typescript-eslint/utils@alpha39` and as such the two get two different versions

I think this is correct behavior, and what users of `neostandard` will also get.

I have asked in the `typescript-eslint` discord channel for version 8 how it comes that `typescript-eslint` is out of sync

2024-07-04 10:35 UTC, jerome-benoit commented
> 
> I think this is correct behavior, and what users of `neostandard` will also get.
> 

The definition of `correct behavior` here differs between package manager. 

And the behavior that enforce: 

- lock file minium size 
- prefer latest leaf dependencies version when possible by default

will fit a space efficient package management design. `pnpm` and `yarn` behaves that way is most case, `npm` not.  

Example: user of `neostandard` with `pnpm` will get a deduped local lock file while `npm` user will get a needlessly oversized lock file with unneeded deps dups. Using `npm dedupe` makes npm behaves closer to `pnpm`.

2024-07-04 10:45 UTC, voxpelli commented
But since the lockfile isn't published it only serves as a reference to the npm based tests that are being run in this repository, to ensure that we catch regressions, so it doesn't really matter here, right?

2024-07-04 10:59 UTC, jerome-benoit commented
> But since the lockfile isn't published it only serves as a reference to the npm based tests that are being run in this repository, to ensure that we catch regressions, so it doesn't really matter here, right?

How many times `npm i` or `npm ci` is run in CI? How many run are cached? What is the installation time between run with and without deduping? What is the cache total size with and without deduping? 

Since the CI in that repo is doing deps installation intensively, I would argue that using a space efficient package manager will make it greener :)

As a side note: you can't imagine the amount of space on SCM hosting infra that will be saved if npm lock file were deduped. 

I will revert the package-lock.json changes to avoid blocking the other change. And open a ticket/discussion on a space efficient CI when time permits.

2024-07-04 12:14 UTC, voxpelli approved these changes

2024-07-04 12:15 UTC, merged